#!/bin/bash

function restartHistory() {
  #This function obliterates a branch
  #$1 is the name of the branch to obliterate
  echo "##restarting history"
  git checkout $1
  git checkout --orphan newbranch
  git add -A
  git commit -am "start over"
  git branch -D $1
  git branch -m $1
  git push -f origin $1

  rm *
  git add -A
  git commit -m "blank files"
  git push -f origin $1
}

function remakeBranch () {
  #This function resets a branch to master's current history
  #$1 is the name of the branch to reset
  echo "##remaking branch"
  git checkout master
  git checkout -b newbranch
  git add -A
  git commit -am "start from master"
  git branch -D $1
  git branch -m $1
  git push -f origin $1
}

#This is the start of the script
#delete the old local version and obliterate it
echo "##starting script"
rm -rf gittester
git clone https://github.com/djshapiro/gittester.git
cd gittester
restartHistory master
git fetch origin v1
git checkout v1
git fetch origin v2
git checkout v2
git checkout master

#Make a file and put some stuff in it
echo "##making a new file"
touch file1
echo "stuff" >> file1
echo "more stuff" >> file1
echo "[1,2,3]" >> file1
git add -A
git commit -m "added some stuff to file1"
git push -f origin master
remakeBranch v1
remakeBranch v2
